spring:
  cloud:
    gateway:
      routes:
        - id: auth_service
          uri: http://localhost:8081
          predicates:
            - Path=/auth/**
        - id: timetable_service
          uri: http://localhost:8082
          predicates:
            - Path=/api/v1/**
